### ISSUE TITLE
roadmap for Azure Dashboards ?

### ISSUE THREAD

**Issue by htalluri9** [cloudquery/dashboards#4]
### Describe the resource.

any roadmap for Azure Dashboards ?

### Use Case

similar to pre-configured dashboards provided for AWS and GCP, checking if there is a plan for supporting Azure

**Comment by yevgenypats** [comment]
Sorry, completely missed this issue. Yeah we plan to expand this but don't have a concrete timeline yet. Feel free to open a PR though, we will be happy to review :)
