### ISSUE TITLE
Queries in AWS Asset Inventory dashboard reference incorrect table

### ISSUE THREAD

**Issue by omkar-yb** [cloudquery/dashboards#9]
### Describe the bug

The queries in this dashboard - https://github.com/cloudquery/dashboards/blob/main/dashboards/aws/aws_asset_inventory.json, reference the `aws_resources` table. However, after `cloudquery fetch` finished, it did not create any table with this name.

Can you please describe how to update the queries?

### Expected Behavior

Table `aws_resources` to be present in the DB

### Steps to Reproduce

Run `cloudquery fetch` for an AWS account, using latest binary.

### Provider and CloudQuery version

Version: 0.27.3, Commit: b3d9091f740a26eefa1f8f9ee8284b4b154be493, cq-provider-aws@v0.12.16

**Comment by NSi1974** [comment]
Hi !
You may find this view, to add to your DB, directly on CQ provider page, here : https://github.com/cloudquery/cq-provider-aws/tree/main/views

**Comment by erezrokah** [comment]
Thanks @NSi1974 and @omkar-yb, I'll close this as resolved. For future reference I'll link this section in our docs https://github.com/cloudquery/dashboards/tree/5db2931637acaf79b6699fa49ecf10f7961951c8#aws
